USE hibernate;

INSERT INTO skills (name)
VALUES ('JavaScript'),
('BigData'),
('MongoDB'),
('DevOps'),
('Java'),
('C#'),
('Ruby on Rails'),
('Python'),
('Django'),
('Node.js'),
('Scala'),
('Go'),
('AngularJS'),
('agile'),
('IaaS'),
('Go'),
('Amazon Web Services'),
('Google Cloud Compute'),
('API'),
('ASP.NET MVC'),
('XML'),
('AJAX'),
('SQL'),
('HTML'),
('CSS'),
('jQuery'),
('OOP');


INSERT INTO developers
VALUES 
(uuid(),'Ilya','Slysarenko','Java Developer',1000.00),
(uuid(),'Denis','Grammakov','C Developer',2000.00),
(uuid(),'Yaroslava','Gagen-Torn','C++ Developer',1500.00),
(uuid(),'Anatoly','Karpenko','Pyton Developer',1700.00),
(uuid(),'Youra','Karpenko','C# Developer',800.00),
(uuid(),'Youra','Krohmal','JavaScript Developer',900.00),
(uuid(),'Alexey','Martynov','Visual Basic .NET Developer',850.00),
(uuid(),'Anton','Dubrovin','PHP Developer',950.00),
(uuid(),'Alexander','Chayko','Delphi Developer',1200.00),
(uuid(),'Sergey','Tarasov','Assembly Developer',750.00),
(uuid(),'Pasha','Fedorov','R Developer',500.00),
(uuid(),'Ilya','Orlov','MatLab Developer',900.00),
(uuid(),'Alexander','Gagen-Torn','Ruby Developer',950.00),
(uuid(),'Sergey','Karashevich','Go Developer',1000.00),
(uuid(),'Sergey','Popov','Perl Developer',2000.00),
(uuid(),'Alexey','Agadjanov','Scratch Developer',1500.00),
(uuid(),'Marya','Belova','PL/SQL Developer',1700.00),
(uuid(),'Anastasya','Akela','Objective-C Developer',800.00),
(uuid(),'Alexander','Melnikov','Swift Developer',900.00),
(uuid(),'Andrey','Sergeevich','Java Developer',850.00),
(uuid(),'Irina','Timkina','Java Developer',950.00),
(uuid(),'Ekaterina','Horina','C++ Developer',1200.00),
(uuid(),'Denis','Elhov','C# Developer',750.00),
(uuid(),'Nikolay','Nimkevich','Java Developer',500.00),
(uuid(),'Max','Ebbert','Pyton Developer',900.00),
(uuid(),'Alexey','Pimanenko','Swift Developer',950.00),
(uuid(),'Olya','Pronevich','JavaScript Developer',1000.00),
(uuid(),'Dmitry','Klochkov','Perl Developer',2000.00),
(uuid(),'Artyom','Savenkov','Ruby Developer',1500.00),
(uuid(),'Nikita','Zadirushko','Go Developer',1700.00),
(uuid(),'Denis','Grammakov','Java Developer',800.00),
(uuid(),'Nade','Syprycheva','Go Developer',900.00),
(uuid(),'Vadim','Volkov','Ruby Developer',850.00),
(uuid(),'Vadim','Grechishin','Swift Developer',950.00),
(uuid(),'Alex','Burmistrova','Pyton Developer',1200.00),
(uuid(),'Chen','Lee','C++ Developer',750.00),
(uuid(),'Fidel','Castro','C# Developer',500.00),
(uuid(),'Alla','Magala','JavaScript Developer',900.00),
(uuid(),'Artur','King','Java Developer',950.00),
(uuid(),'Burushka','Horse','Go Developer',1000.00),
(uuid(),'Samanta	','	Alabama	','	Ruby Developer	',2000.00),
(uuid(),'Kim','Karandash','Swift Developer',1500.00),
(uuid(),'Seka','Beka','Pyton Developer',1700.00),
(uuid(),'Boka','Voka','C++ Developer',800.00),
(uuid(),'Semyon','Slepakov','C# Developer',900.00),
(uuid(),'Gosha','Kosha','JavaScript Developer',850.00),
(uuid(),'Kung','Lao','Java Developer',950.00),
(uuid(),'Seva','Melnikov','Java Developer',1200.00),
(uuid(),'Alla','Malysheva','Go Developer',750.00),
(uuid(),'Akella','Miss','Ruby Developer',500.00),
(uuid(),'Bred','Dead','Swift Developer',900.00),
(uuid(),'John','Dow','Pyton Developer',950.00),
(uuid(),'Ilya','Slysarenko','Java Developer',0.00),
(uuid(),'Denis','Grammakov','C Developer',0.00),
(uuid(),'Yaroslava','Gagen-Torn','C++ Developer',0.00),
(uuid(),'Anatoly','Karpenko','Pyton Developer',0.00),
(uuid(),'Youra','Karpenko','C# Developer',0.00),
(uuid(),'Youra','Krohmal','JavaScript Developer',0.00),
(uuid(),'Alexey','Martynov','Visual Basic .NET Developer',0.00),
(uuid(),'Anton','Dubrovin','PHP Developer',0.00),
(uuid(),'Alexander','Chayko','Delphi Developer',0.00),
(uuid(),'Sergey','Tarasov','Assembly Developer',0.00),
(uuid(),'Pasha','Fedorov','R Developer',0.00),
(uuid(),'Ilya','Orlov','MatLab Developer',0.00),
(uuid(),'Alexander','Gagen-Torn','Ruby Developer',0.00),
(uuid(),'Sergey','Karashevich','Go Developer',0.00),
(uuid(),'Sergey','Popov','Perl Developer',0.00),
(uuid(),'Alexey','Agadjanov','Scratch Developer',0.00),
(uuid(),'Marya','Belova','PL/SQL Developer',0.00),
(uuid(),'Anastasya','Akela','Objective-C Developer',0.00),
(uuid(),'Alexander','Melnikov','Swift Developer',0.00),
(uuid(),'Andrey','Sergeevich','Java Developer',0.00),
(uuid(),'Irina','Timkina','Java Developer',0.00),
(uuid(),'Ekaterina','Horina','C++ Developer',0.00),
(uuid(),'Denis','Elhov','C# Developer',0.00),
(uuid(),'Nikolay','Nimkevich','Java Developer',0.00),
(uuid(),'Max','Ebbert','Pyton Developer',0.00),
(uuid(),'Alexey','Pimanenko','Swift Developer',0.00),
(uuid(),'Olya','Pronevich','JavaScript Developer',0.00),
(uuid(),'Dmitry','Klochkov','Perl Developer',0.00),
(uuid(),'Artyom','Savenkov','Ruby Developer',0.00),
(uuid(),'Nikita','Zadirushko','Go Developer',0.00);

INSERT INTO teams
VALUES 
(uuid(),'alpha'),
(uuid(),'beta'),
(uuid(),'gamma'),
(uuid(),'delta'),
(uuid(),'epsilon'),
(uuid(),'zeta'),
(uuid(),'eta'),
(uuid(),'theta'),
(uuid(),'iota'),
(uuid(),'kappa'),
(uuid(),'lambda'),
(uuid(),'mu'),
(uuid(),'nu'),
(uuid(),'xi'),
(uuid(),'omicron'),
(uuid(),'pi'),
(uuid(),'rho'),
(uuid(),'sigma'),
(uuid(),'tau'),
(uuid(),'upsilon'),
(uuid(),'phi'),
(uuid(),'chi'),
(uuid(),'psi'),
(uuid(),'omega');

INSERT INTO projects
VALUES (uuid(),'Music App'),
(uuid(),'Scary Channel'),
(uuid(),'Robocorp'),
(uuid(),'ScIO'),
(uuid(),'Dash'),
(uuid(),'PonoPlayer'),
(uuid(),'Coolest Cooler'),
(uuid(),'Ritot'),
(uuid(),'Jibo'),
(uuid(),'Skully AR-1'),
(uuid(),'TouchPico'),
(uuid(),'ZEN Thermostat');

INSERT INTO companies
VALUES (uuid(),'Google'),
(uuid(),'Yandex'),
(uuid(),'ALibaba'),
(uuid(),'Amazon');

INSERT INTO customers
VALUES (uuid(),'Piter','Parker','U.S.'),
(uuid(),'Bill','Gates','U.S.'),
(uuid(),'Warren','Buffett','U.S.'),
(uuid(),'Jeff','Bezos','U.S.'),
(uuid(),'Amancio','Ortega','Spain'),
(uuid(),'Mark','Zuckerberg','U.S.'),
(uuid(),'Carlos','Slim Helu','Mexico'),
(uuid(),'Larry','Ellison','U.S.'),
(uuid(),'Charles','Koch','U.S.'),
(uuid(),'David','Koch','U.S.'),
(uuid(),'Michael','Bloomberg','U.S.'),
(uuid(),'Bernard','Arnault','France');