USE hibernate;

INSERT INTO skills (name)
VALUES ('JavaScript'),
('BigData'),
('MongoDB'),
('DevOps'),
('Java'),
('C#'),
('Ruby on Rails'),
('Python'),
('Django'),
('Node.js'),
('Scala'),
('Go'),
('AngularJS'),
('agile'),
('IaaS'),
('Go'),
('Amazon Web Services'),
('Google Cloud Compute'),
('API'),
('ASP.NET MVC'),
('XML'),
('AJAX'),
('SQL'),
('HTML'),
('CSS'),
('jQuery'),
('OOP');

INSERT INTO developers (firstName, lastName, specialty, salary)
VALUES 
('Ilya','Slysarenko','Java Developer',1000.00),
('Denis','Grammakov','C Developer',2000.00),
('Yaroslava','Gagen-Torn','C++ Developer',1500.00),
('Anatoly','Karpenko','Pyton Developer',1700.00),
('Youra','Karpenko','C# Developer',800.00),
('Youra','Krohmal','JavaScript Developer',900.00),
('Alexey','Martynov','Visual Basic .NET Developer',850.00),
('Anton','Dubrovin','PHP Developer',950.00),
('Alexander','Chayko','Delphi Developer',1200.00),
('Sergey','Tarasov','Assembly Developer',750.00),
('Pasha','Fedorov','R Developer',500.00),
('Ilya','Orlov','MatLab Developer',900.00),
('Alexander','Gagen-Torn','Ruby Developer',950.00),
('Sergey','Karashevich','Go Developer',1000.00),
('Sergey','Popov','Perl Developer',2000.00),
('Alexey','Agadjanov','Scratch Developer',1500.00),
('Marya','Belova','PL/SQL Developer',1700.00),
('Anastasya','Akela','Objective-C Developer',800.00),
('Alexander','Melnikov','Swift Developer',900.00),
('Andrey','Sergeevich','Java Developer',850.00),
('Irina','Timkina','Java Developer',950.00),
('Ekaterina','Horina','C++ Developer',1200.00),
('Denis','Elhov','C# Developer',750.00),
('Nikolay','Nimkevich','Java Developer',500.00),
('Max','Ebbert','Pyton Developer',900.00),
('Alexey','Pimanenko','Swift Developer',950.00),
('Olya','Pronevich','JavaScript Developer',1000.00),
('Dmitry','Klochkov','Perl Developer',2000.00),
('Artyom','Savenkov','Ruby Developer',1500.00),
('Nikita','Zadirushko','Go Developer',1700.00),
('Denis','Grammakov','Java Developer',800.00),
('Nade','Syprycheva','Go Developer',900.00),
('Vadim','Volkov','Ruby Developer',850.00),
('Vadim','Grechishin','Swift Developer',950.00),
('Alex','Burmistrova','Pyton Developer',1200.00),
('Chen','Lee','C++ Developer',750.00),
('Fidel','Castro','C# Developer',500.00),
('Alla','Magala','JavaScript Developer',900.00),
('Artur','King','Java Developer',950.00),
('Burushka','Horse','Go Developer',1000.00),
('Samanta	','	Alabama	','	Ruby Developer	',2000.00),
('Kim','Karandash','Swift Developer',1500.00),
('Seka','Beka','Pyton Developer',1700.00),
('Boka','Voka','C++ Developer',800.00),
('Semyon','Slepakov','C# Developer',900.00),
('Gosha','Kosha','JavaScript Developer',850.00),
('Kung','Lao','Java Developer',950.00),
('Seva','Melnikov','Java Developer',1200.00),
('Alla','Malysheva','Go Developer',750.00),
('Akella','Miss','Ruby Developer',500.00),
('Bred','Dead','Swift Developer',900.00),
('John','Dow','Pyton Developer',950.00),
('Ilya','Slysarenko','Java Developer',0.00),
('Denis','Grammakov','C Developer',0.00),
('Yaroslava','Gagen-Torn','C++ Developer',0.00),
('Anatoly','Karpenko','Pyton Developer',0.00),
('Youra','Karpenko','C# Developer',0.00),
('Youra','Krohmal','JavaScript Developer',0.00),
('Alexey','Martynov','Visual Basic .NET Developer',0.00),
('Anton','Dubrovin','PHP Developer',0.00),
('Alexander','Chayko','Delphi Developer',0.00),
('Sergey','Tarasov','Assembly Developer',0.00),
('Pasha','Fedorov','R Developer',0.00),
('Ilya','Orlov','MatLab Developer',0.00),
('Alexander','Gagen-Torn','Ruby Developer',0.00),
('Sergey','Karashevich','Go Developer',0.00),
('Sergey','Popov','Perl Developer',0.00),
('Alexey','Agadjanov','Scratch Developer',0.00),
('Marya','Belova','PL/SQL Developer',0.00),
('Anastasya','Akela','Objective-C Developer',0.00),
('Alexander','Melnikov','Swift Developer',0.00),
('Andrey','Sergeevich','Java Developer',0.00),
('Irina','Timkina','Java Developer',0.00),
('Ekaterina','Horina','C++ Developer',0.00),
('Denis','Elhov','C# Developer',0.00),
('Nikolay','Nimkevich','Java Developer',0.00),
('Max','Ebbert','Pyton Developer',0.00),
('Alexey','Pimanenko','Swift Developer',0.00),
('Olya','Pronevich','JavaScript Developer',0.00),
('Dmitry','Klochkov','Perl Developer',0.00),
('Artyom','Savenkov','Ruby Developer',0.00),
('Nikita','Zadirushko','Go Developer',0.00);

INSERT INTO teams
VALUES 
('alpha'),
('beta'),
('gamma'),
('delta'),
('epsilon'),
('zeta'),
('eta'),
('theta'),
('iota'),
('kappa'),
('lambda'),
('mu'),
('nu'),
('xi'),
('omicron'),
('pi'),
('rho'),
('sigma'),
('tau'),
('upsilon'),
('phi'),
('chi'),
('psi'),
('omega');

INSERT INTO projects
VALUES (uuid(),'Music App'),
(uuid(),'Scary Channel'),
(uuid(),'Robocorp'),
(uuid(),'ScIO'),
(uuid(),'Dash'),
(uuid(),'PonoPlayer'),
(uuid(),'Coolest Cooler'),
(uuid(),'Ritot'),
(uuid(),'Jibo'),
(uuid(),'Skully AR-1'),
(uuid(),'TouchPico'),
(uuid(),'ZEN Thermostat');

INSERT INTO companies
VALUES (uuid(),'Google'),
(uuid(),'Yandex'),
(uuid(),'ALibaba'),
(uuid(),'Amazon');

INSERT INTO customers
VALUES (uuid(),'Piter','Parker','U.S.'),
(uuid(),'Bill','Gates','U.S.'),
(uuid(),'Warren','Buffett','U.S.'),
(uuid(),'Jeff','Bezos','U.S.'),
(uuid(),'Amancio','Ortega','Spain'),
(uuid(),'Mark','Zuckerberg','U.S.'),
(uuid(),'Carlos','Slim Helu','Mexico'),
(uuid(),'Larry','Ellison','U.S.'),
(uuid(),'Charles','Koch','U.S.'),
(uuid(),'David','Koch','U.S.'),
(uuid(),'Michael','Bloomberg','U.S.'),
(uuid(),'Bernard','Arnault','France');